import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { LenisProvider } from "../components/lenis-provider";

import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Navbar } from "../components/navbar/navbar";
import { Footer } from "../components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={"antialiased font-normal"}
        style={{ fontFamily: "var(--primary-font)" }}
      >
        <NextIntlClientProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <LenisProvider>
              <main className="relative text-accent-foreground">
                <Navbar locale={locale} />
                {children}
                <Footer />
              </main>
            </LenisProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
